### PR TITLE
Is vcsroot svn

### PR DESCRIPTION
**Pull request by weswigham**
Yes. Yes it is.

### CODE REVIEW

**Comment by derekerdmann** [comment]
Won't this show every directory inside the repo as an SVN root? I thought .svn folders got littered all across the local copy of the repo

**Comment by weswigham** [comment]
Not in any of the new repos I have at work, I checked. I think that's a relic of either an older version of the svn protocol or older svn clients.

**Comment by derekerdmann** [comment]
I'm ok with not supporting older versions of SVN unless we need to

**Comment by weswigham** [comment]
The worst part is that I haven't actually found any documentation to support this, this is just observed from a larger number of svn repos checkout out via both command line svn and tortoise svn on windows. Normally I'd link some kind of documentation backing me up.

**Comment by weswigham** [comment]
Ah! Found it! [Subversion 1.7 release notes!~](http://subversion.apache.org/docs/release-notes/1.7.html) Under "Centralized Metadata Storage". Apache doesn't even support svn versions older than 1.7.

**Pull request merged**
